// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cqPqdm5dVjtUHr8PKgNf76
// Component: zfaRL9tc0WRN
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: cqPqdm5dVjtUHr8PKgNf76/projectcss
import sty from "./PlasmicMnDashboard.module.css"; // plasmic-import: zfaRL9tc0WRN/css

createPlasmicElementProxy;

export const PlasmicMnDashboard__VariantProps = new Array();

export const PlasmicMnDashboard__ArgProps = new Array();

const $$ = {};

function PlasmicMnDashboard__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <h1
        data-plasmic-name={"mnHeader"}
        data-plasmic-override={overrides.mnHeader}
        className={classNames(
          projectcss.all,
          projectcss.h1,
          projectcss.__wab_text,
          sty.mnHeader
        )}
      >
        {"MobiNav Dashboard"}
      </h1>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "mnHeader"],
  mnHeader: ["mnHeader"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMnDashboard__ArgProps,
          internalVariantPropNames: PlasmicMnDashboard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMnDashboard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMnDashboard";
  } else {
    func.displayName = `PlasmicMnDashboard.${nodeName}`;
  }
  return func;
}

export const PlasmicMnDashboard = Object.assign(
  // Top-level PlasmicMnDashboard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    mnHeader: makeNodeComponent("mnHeader"),
    // Metadata about props expected for PlasmicMnDashboard
    internalVariantProps: PlasmicMnDashboard__VariantProps,
    internalArgProps: PlasmicMnDashboard__ArgProps
  }
);

export default PlasmicMnDashboard;
/* prettier-ignore-end */
